export const apiEndPoints = {
  login: `/auth/login`,
  googleLogin: `/auth/google/google-redirect`,
  register: `/auth/register`,
  tasks: `/tasks`,
  export: `/export`,
  syncTasks: `/tasks/sync`,
  syncStatus: `/tasks/sync/status`,
  sessions: `/sessions`,
  deleteSession: `/tasks/delete-session/`,
  jira: `/integrations/jira`,
  integrations: `/integrations`,
  notifications: `/notifications`,
  authJira: `/integrations/jira/authorization`,
  spentTime: `/tasks/spent-time/time-range`,
  spentTimePerDay: `/tasks/spent-time/per-day`,
  addWorkLog: `/sessions/add-work-log`,
  updateTaskStatus: `/tasks/update/status`,
  projectWiseStatus: `/integrations/jira/projects`,
};
