export const apiEndPoints = {
  login: `/auth/login`,
  googleLogin: `/auth/google/google-redirect`,
  register: `/auth/register`,
  tasks: `/tasks`,
  export: `/export`,
  syncTasks: `/tasks/sync`,
  syncStatus: `/tasks/sync/status`,
  sessions: `/sessions`,
  jira: `/integrations/jira`,
  integrations: `/integrations`,
  authJira: `/auth/jira`,
  spentTime: `/tasks/spent-time/time-range`,
  spentTimePerDay: `/tasks/spent-time/per-day`,
};
